language: node_js
node_js: lts/*

cache:
  npm: true
  directories:
  - $HOME/.pnpm-store/

branches:
  only:
  - master

before_install:
- curl -L https://unpkg.com/@pnpm/self-installer | node

install:
- pnpm i

script:
- pnpm recursive run bundle
# - pnpm recursive pack
- (cd ./packages/docs && pnpm run build)

deploy:
  on:
    branch: master
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: ./packages/docs/storybook-static

# deploy:
# provider: npm
# tag: next
