language: node_js
node_js: lts/*

cache:
  npm: true
  directories:
  - $HOME/.pnpm-store/

branches:
  only:
  - master

before_install:
- curl -L https://unpkg.com/@pnpm/self-installer | node

install:
- pnpm i

jobs:
- name: Pre-Release
  if: type == pull_request
  script:
  - pnpm recursive exec pnpm version prerelease -- --preid next
  - pnpm recursive run bundle
  - pnpm recursive exec pnpm pack
- name: Release
  if: type == push
  script:
  - pnpm recursive exec pnpm version patch
  - pnpm recursive run bundle
  - pnpm recursive exec pnpm pack
  - (cd ./packages/docs && pnpm run build)

after_success:
- git commit -am "[skip ci] updated version"
- git push origin HEAD:$TRAVIS_BRANCH

deploy:
- provider: npm
  on:
    type: pull_request
    branch: master
  cleanup: false
  email: $NPM_EMAIL_ADDRESS
  api_token: $NPM_AUTH_TOKEN
  tag: next
- provider: npm
  on:
    type: push
    branch: master
  cleanup: false
  email: $NPM_EMAIL_ADDRESS
  api_token: $NPM_AUTH_TOKEN
- provider: pages
  on:
    type: push
    branch: master
  cleanup: false
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: ./packages/docs/storybook-static
