language: node_js
node_js: lts/*

cache:
  npm: true
  directories:
  - $HOME/.pnpm-store/

branches:
  only:
  - master

before_install:
- curl -L https://unpkg.com/@pnpm/self-installer | node

install:
- pnpm i

jobs:
- name: build
  script:
  - pnpm recursive exec pnpm version patch
  - pnpm recursive run bundle
  - (cd ./packages/docs && pnpm run build)

deploy:
- provider: npm
  on:
    branch: master
  cleanup: false
  email: $NPM_EMAIL_ADDRESS
  api_token: $NPM_AUTH_TOKEN
- provider: pages
  on:
    branch: master
  cleanup: false
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: ./packages/docs/storybook-static
